#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Make sure that HAproxy can be managed via an init script
sudo apt-get -y update
sudo apt-get -y install haproxy

echo \
"
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend
backend lb-backend
        balance roundrobin
        server 5846-web-01 54.167.1.174:80 check
        server 5846-web-02 54.226.25.73:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
